### ISSUE TITLE
Support JSON_ARRAYAGG, JSON_OBJECTAGG  aggregate functions

### ISSUE THREAD

**Issue by elonzh** [adamchainz/django-mysql#1048]
### Description

`JSON_ARRAYAGG` and `JSON_OBJECTAGG `  are better than `GROUP_CONCAT` when we want to get aggregated values.

- [MySQL :: MySQL 8.0 Reference Manual :: 12.19.1 Aggregate Function Descriptions](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_json-arrayagg)
- [JSON_ARRAYAGG - MariaDB Knowledge Base](https://mariadb.com/kb/en/json_arrayagg/)

**Comment by adamchainz** [comment]
These are probably candidates for adding to Django at this point. `JSONField` supports all core databases and I would think such aggregation could be possible on most or all of them. Propose this in the forum with some code?
