### ISSUE TITLE
Support reverse ordering for Smart Iteration

### ISSUE THREAD

**Issue by lwiecek** [adamchainz/django-mysql#129]
Let's say our queryset looks like is so:
`qs = MyModel.objects.all()`

`list(qs.iter_smart())` returns non-empty list
`list(qs.reverse().iter_smart())` returns empty list `[]`

The bug is caused by a `max_pk` and `min_pk` assuming `min_pk <= max_pk` which isn't the case for `reverse`.
https://github.com/adamchainz/django-mysql/blob/66788e709c7b5196a9bc3f97f17993f039be9e36/django_mysql/models/query.py#L173

**Comment by adamchainz** [comment]
`reverse()` isn't necessarily the right thing to be calling, as it just means "invert" the ordering - you might mean `order_by('-pk')`. However it is true that SmartIterator is assuming forwards PK order - e.g. line 223 `min_qs = base_qs.order_by('pk').values_list('pk', flat=True)`.

Ideally it would work with, and only with, ordering set to `order_by('pk')` or `order_by('-pk')`.
