### ISSUE TITLE
FoundRowsPaginator

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#151]
Using `sql_calc_found_rows` from #115 , a paginator could be built that uses a single select query rather than one to generate the count and another to get the data. This can often, but not always, be faster - see [this percona blogpost](https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/).

N.B. I started on this during implementation in #150 , but dropped the paginator since it was getting too complex and would probably require some features dropping, like `orphans`. The code still sits here on a branch at https://github.com/adamchainz/django-mysql/tree/found_rows_paginator

**Comment by jheld** [comment]
Sql calc found rows is going away in mysql 8.0. Not that this couldn't still be implemented of course. (Though we should update the docs for sql calc found rows to note this)

**Comment by adamchainz** [comment]
I can't find any evidence that it's going to be removed in MariaDB - they tend to keep things for longer to support more applications.

**Comment by adamchainz** [comment]
Meh this is probably not worth it if it's gone in MySQL, and cursor-based pagination is more efficient if you want that efficiency.
