### ISSUE TITLE
Smart Iteration add chunk_min

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#156]
For some sparse/clustered queries, the chunk size can be pushed to a small value and stay there whilst iterating over the "empty"/unmatching rows between the clusters of results. Although there are smarter things we could try to skip over these holes, a minimum bound to the chunk size would be a simple control to prevent these many useless queries.

**Comment by adamchainz** [comment]
@babbageclunk

**Comment by babbageclunk** [comment]
I guess trying to grow the chunk size after seeing lots of empty ones runs the risk of suddenly hitting a big cluster and hogging the DB?

**Comment by adamchainz** [comment]
Yes see #111

**Comment by adamchainz** [comment]
@lwiecek is on this

**Comment by lwiecek** [comment]
commited https://github.com/adamchainz/django-mysql/commit/01437dd1f09ceb5b6f19c68d91a136fc591e682f

**Comment by adamchainz** [comment]
Fixed in #180
