### ISSUE TITLE
test_cache.py fails on ubuntu linux with django 1.7

### ISSUE THREAD

**Issue by MichaelAquilina** [adamchainz/django-mysql#188]
Discovered this while using tox, the following combination consistently fails on master:

```
msql version: 5.6.27-0ubuntu1
branch: master
Python 2.7.8
Django version: 1.7.10.final.0
```

Tested this on my personal and work laptop. Numerous tests in test_cache.py fail with the following message:

```
self = <tests.testapp.test_cache.MySQLCacheTests testMethod=test_keys_with_prefix_version_4_custom_key2>

    @wraps(func)
    def wrapper(self):
>       return func(self, *args, **kwargs)

.tox/py27-django17/local/lib/python2.7/site-packages/ddt.py:146: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/testapp/test_cache.py:1113: in test_keys_with_prefix_version
    cache.set('V12', True, version=1)
django_mysql/cache.py:204: in set
    self._base_set('set', key, value, timeout)
django_mysql/cache.py:228: in _base_set
    cursor.execute(query.format(table=table), params)
.tox/py27-django17/local/lib/python2.7/site-packages/django/db/backends/utils.py:65: in execute
    return self.cursor.execute(sql, params)
django_mysql/monkey_patches.py:42: in execute
    return orig_execute(self, sql, args)
.tox/py27-django17/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py:129: in execute
    return self.cursor.execute(query, args)
.tox/py27-django17/local/lib/python2.7/site-packages/MySQLdb/cursors.py:222: in execute
    if not self._defer_warnings: self._warning_check()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MySQLdb.cursors.Cursor object at 0x7fd2c1531950>

    def _warning_check(self):
        from warnings import warn
        if self._warnings:
            warnings = self._get_db().show_warnings()
            if warnings:
                # This is done in two loops in case
                # Warnings are set to raise exceptions.
                for w in warnings:
                    self.messages.append((self.Warning, w))
                for w in warnings:
>                   warn(w[-1], self.Warning, 3)
E                   Warning: Invalid utf8mb4 character string: '800288'
```
the utf8mb4 character string value changes between each test, but the error is basically the same.

**Comment by MichaelAquilina** [comment]
seems like its to do with the fact that warnings is set to "error" for that configuration for some reason.... using --pdb and running `warnings.resetwarnings()` prevents the rest of the errors from being raised when you continue.

**Comment by MichaelAquilina** [comment]
Are you expecting to store 'value' as the pickled value '\x80\x02X\x05\x00\x00\x00valueq\x01.' in the database? I'm guessing this is the reason the warning is being raised and causing the test to fail.

**Comment by MichaelAquilina** [comment]
Fails on python3.4 too

**Comment by adamchainz** [comment]
Expecting to store `'value'` as whatever `pickle.dumps(value, pickle.HIGHEST_PROTOCOL)` is - it's `'\x80\x02X\x05\x00\x00\x00valueq\x00.'` on my machine - subtly different at the end there.

I have a feeling it's something even more specific to your setup since MySQL 5.6 / ubuntu / Django 1.7 ? Pythons 2.7 and 3.4 are all tested together on Travis and the test passes...

**Comment by adamchainz** [comment]
What version of `mysqlclient` are you using? Presumably you've just done `pip install -r requirements.txt` so you have the latest one in that file, right?

**Comment by MichaelAquilina** [comment]
Everything was tested through tox, so it should have installed all the correct requirements. Both my work and personal laptop are running ubuntu 15.10 which could have different versions of mysql installed.

**Comment by adamchainz** [comment]
Well indeed, Travis is using `MySQL version: 5.6.24-2+deb.sury.org~precise+2`. I think it's from an unofficial repository so I'll look into an official one - maybe there are configuration differences.

**Comment by adamchainz** [comment]
I'm also getting this warning on #155 . It may actually be linked to mysqlclient...

**Comment by adamchainz** [comment]
This has started happening on Travis too with their new build infrastructure as per #198 , on MySQL 5.5 only, and with these environments only:

```
ERROR:   py34-django18: commands failed
ERROR:   py34-django19: commands failed
ERROR:   py35-django18: commands failed
ERROR:   py35-django19: commands failed
ERROR:   py27-django17: commands failed
ERROR:   py34-django17: commands failed
The command "tox" exited with 1.
```

I do think it's something to do with `mysqlclient`, possibly compile-time.

**Comment by adamchainz** [comment]
This looks like a bug in either MySQL or `libmysqlclient` - can you try testing on the 5.6 version distributed by Oracle? https://dev.mysql.com/downloads/repo/apt/
