### ISSUE TITLE
approx_count can go further

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#21]
The `approx_count` function can be used to count `QuerySet`s other than the basic full-table ones it accepts at current. For example, you can get a reliable(-ish) approximate count on an index range, such as `id BETWEEN 1 AND 500` (with id = primary key). This would make it much more useful too.

**Comment by jheld** [comment]
What might be involved with implementing this?

We use approx count in some places in django admin so any improvements/extensions would be great to have.

**Comment by adamchainz** [comment]
The idea is to expand [`can_approx_count`](https://github.com/adamchainz/django-mysql/blob/2e4bb08488f737306f22b29ff217e2a33823d276/src/django_mysql/models/query.py#L589) to cover other situations, without hitting false positives.

Looking again at it, I'm not sure how feasible it is, given the information we have in Django about the database layout and the complexity of introspecting every possible modification to a `QuerySet`.

**Comment by adamchainz** [comment]
I think this is probably too hard.
