### ISSUE TITLE
JSONField spec support like DynamicField

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#245]
Summary: The `spec` argument to `DynamicField` is useful for enforcing extra constraints on the data, which could also be useful in `JSONField` - in fact, maybe more so, since it would enforce the value being a `dict`/JSON object, which is a slight worry.

The `spec` code from `DynamicField` would need significant extension to do this though, since JSON has many more types, plus validation gets complicated with `list`s

**Comment by sergiomb2** [comment]
NotImplementedError: Lookup 'search' doesn't work with JSONField

btw also would be nice the in operator 

    NotImplementedError: Lookup 'in' doesn't work with JSONField

and also I miss order_by  JSON Path .

Best regards.

**Comment by adamchainz** [comment]
I won't be doing this as will be standardizing on the [Django 3.1 universal `JSONField`](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends)
