### ISSUE TITLE
ImportError: No module named termios on Windows

### ISSUE THREAD

**Issue by MrCsabaToth** [adamchainz/django-mysql#272]
Summary: https://stackoverflow.com/questions/36508126/importerror-no-module-named-termios-with-django-mysql-on-windows

Django Version: 1.8.7
Database and version used: MySQL 5.6
Version: Django-MySQL 1.0.7

Even after installing Cygwin.

**Comment by MrCsabaToth** [comment]
Looks like here pty is the culprit too? https://github.com/mwilliamson/spur.py/issues/16

**Comment by adamchainz** [comment]
Just pushing a fix in #273, when it builds I'll push it to PyPI.

Sorry about this, maybe you're the first Windows user!

**Comment by adamchainz** [comment]
Version 1.0.8 deployed on PyPI, tell me how that works for you! https://pypi.python.org/pypi/django-mysql

**Comment by MrCsabaToth** [comment]
Thanks, that was fast! I monkey patched mine and I confirm that I don't have that particular error any more.

**Comment by MrCsabaToth** [comment]
Worked!

**Comment by adamchainz** [comment]
🌈

**Comment by Garthoomh** [comment]
I couldn't install it? How can I add it to my python code?

**Comment by adamchainz** [comment]
@Garthoomh are you looking for this? https://django-mysql.readthedocs.io/en/latest/installation.html

**Comment by Garthoomh** [comment]
Hi thank you very much for your fast reply. However, I follow the instruction of  downloading (pip install django-mysql). I'm trying to run this code: https://github.com/venthur/python-ardrone 
in my machine which is windows. I would appreciate your help.

**Comment by adamchainz** [comment]
That code doesn't use django-mysql. You should report an error on that repo that it doesn't work on windows. I can't help you here, I only maintain django-mysql.

**Comment by Abhimanyu100** [comment]
@adamchainz I'm trying to run one of my Machine learning project in vscode, it run fine on Google Cloab but when running on vscode, it throws an error  `ModuleNotFoundError: No module named 'termios' on searching I found that termios is not available for windows. Any way to resolve error?
`

**Comment by adamchainz** [comment]
@Abhimanyu100 does your code use Django-MySQL? It's  not a machine learning  library.
