### ISSUE TITLE
JSONField default with lambda doesn't work with django migration

### ISSUE THREAD

**Issue by eagle21st** [adamchainz/django-mysql#340]
Summary: *When using `JSONField` with `defaul=lambda:{foo:bar}`, django `makemigration` command thwos `ValueError: Cannot serialize function: lambda`*

Django Version: *Django 1.10.3*

Database and version used: *MySQL 5.7*

Version: *Django-MySQL 1.1.0*

**Comment by adamchainz** [comment]
The solution to this is to create a function that's importable at the module scope e.g.

```
def my_default():
    return {'foo': 'bar'}

class MyModel(Model):
    my_field = JSONField(default=my_default)
```

I'll update the docs to stop recommending the use of `lambda`.
