### ISSUE TITLE
Numpy NaN is not supported by JSON.

### ISSUE THREAD

**Issue by arnau126** [adamchainz/django-mysql#345]
Summary: NaN is not in the JSON specification, so when you try to save a django model which contains a numpy nan, it crashes with a misleading error message:

> InterfaceError: (-1, 'error totally whack')

I wonder if it is possible for django_mysql to also serialize NaN (as json.dumps does).

If not, at least raise an easier to understand message error.
This could be achieve by calling json.dumps with allow_nan=False.
Doing this, the raised error would be:

> ValueError: Out of range float values are not JSON compliant

(and is raised by json.dumps function, instead of by the DB)

Django Version: *Django 1.10.6*

Database and version used: *MySQL 5.7*

Version: *Django-MySQL 1.1.0*

**Comment by adamchainz** [comment]
Is it `numpy.nan` or `float('nan')` you're having a problem with?

Anyway seems like we could just pass `allow_nan=False` to `json.dumps` in the field here: https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L102

**Comment by arnau126** [comment]
@adamchainz 

> Is it numpy.nan or float('nan') you're having a problem with?

Both, since json.dumps serializes both in the same way.

> Anyway seems like we could just pass allow_nan=False to json.dumps in the field here: https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L102

Yes, this is what I meant.

**Comment by adamchainz** [comment]
Ok PR welcome!

**Comment by arnau126** [comment]
PR: #346
