### ISSUE TITLE
Add JSON Create & Modify MySQL functions 

### ISSUE THREAD

**Issue by avelis** [adamchainz/django-mysql#347]
Summary: To have the ability to use MySQL JSON functions that can create and modify data as Django ORM expressions and/or functions.

e.g.
```python
shop_item.attrs = JSONSet(F('attrs'), {'$.smelliness': 10, '$.color': 'magenta'})
```
This is one interpretation of what I am essentially getting at. It could be possible that the JSONSet class could also augment the keys to prepend the `$.` string.

I could attempt a PR for this but would like some direction on this.

**Comment by adamchainz** [comment]
Yes I agree they would be good to add. I think I'm against the key-augmentation thing, because the keys in that dict would be json paths and could feature complex expressions like `$.colours[0][1]`.

**Comment by avelis** [comment]
@adamchainz ok, that makes sense.

**Comment by avelis** [comment]
```

**Comment by adamchainz** [comment]
would prefer it in a pull-request with tests :)

Also the `len` thing would be better done at the top with a check on `pairs` being a dict of at least one key.

**Comment by avelis** [comment]
@adamchainz I can make a PR. I wrote this up in the late hours of the night and felt it needed a second eye before making a PR.

**Comment by adamchainz** [comment]
PR = second set of eyes at code review 😉

**Comment by avelis** [comment]
ha! Fair enough.
