### ISSUE TITLE
"manage.py dumpdata" uses str instead of json.dumps on JSONField

### ISSUE THREAD

**Issue by dangle** [adamchainz/django-mysql#353]
Summary: Running ./manage.py dumpdata dumps the the JSONField as a Python dictionary string instead of a JSON string.

e.g.

```json
[
    {
        "model": "myapp.mymodel",
        "pk": 1,
        "fields": {
            "my_json_field": "{'field1': None, 'field2': False}"
        }
    }
]
```

instead of 

```json
[
    {
        "model": "myapp.mymodel",
        "pk": 1,
        "fields": {
            "my_json_field": "{\"field1\": null, \"field2\": false}"
        }
    }
]
```

*If this is a bug, please fill in the below, else delete*

Django Version: Django 1.10.6

Database and version used: MySQL 5.7

Version: Django-MySQL 1.1.1

**Comment by adamchainz** [comment]
Aha! We probably need to add some extra methods to the field to support the serializers. Have you had a look at how `django.contrib.postgres` works with `dumpdata`?

**Comment by dangle** [comment]
I looks like the field just needs a `value_to_string()` method.

[Postgres version](https://github.com/django/django/blob/master/django/contrib/postgres/fields/jsonb.py#L73) and [Django docs](https://docs.djangoproject.com/en/1.11/howto/custom-model-fields/#converting-field-data-for-serialization)
