### ISSUE TITLE
Does the mariadb required for django-mysql module ?

### ISSUE THREAD

**Issue by shashanks1** [adamchainz/django-mysql#357]
Summary: *Got this error when run makemigrations for JSONField AttributeError: 'DatabaseWrapper' object has no attribute 'is_mariadb'*

*If this is a bug, please fill in the below, else delete*

Django Version: Django 1.10.5

Database and version used: MySQL 5.7

Version: django-mysql==1.1.1

**Comment by adamchainz** [comment]
No it's not, this is a known error #323, you need to follow the install instructions at https://django-mysql.readthedocs.io/en/latest/installation.html as I just told you on #331.

**Comment by shashanks1** [comment]
Hey I am using django version 1.10.5 and I suspect might be this is the reason I got the DatabaseWrapper error. I went through the json.py in models and saw the function `_check_mysql_version` there you expect connection object must have is_mariadb attribute, but If someone do not installed the mariadb how does  connection object know then mariadb attribute.
