### ISSUE TITLE
Integration with Django REST framework and django-filter, Meta.filter_overrides ? to make AutoFilterSet work ? 

### ISSUE THREAD

**Issue by sergiomb2** [adamchainz/django-mysql#358]
Summary: *summarize the issue here*

*If this is a bug, please fill in the below, else delete*

Django Version: *1.11*

Database and version used: *MySQL Community 5.7.17*

Version: *1.1.1 + more 7 commit in master*

AutoFilterSet resolved field 'parameters' with 'exact' lookup to an unrecognized field type JSONField. Try adding an override to 'Meta.filter_overrides'. See: https://django-filter.readthedocs.io/en/develop/ref/filterset.html#customise-filter-generation-with-filter-overrides

It was nice have autofilter working with JSONField . 

Thanks.

**Comment by adamchainz** [comment]
Sorry I don't use `django-filter`. Please provide more information on how to replicate, such as an example project

**Comment by sergiomb2** [comment]
yes, you need install django-filter  and djangorestframework (3.6.2) and just follow http://www.django-rest-framework.org/api-guide/filtering/#setting-filter-backends

```
class SomethingList(generics.ListCreateAPIView):
    """
    List the somethings available
    """
    filter_backends = (filters.SearchFilter, DjangoFilterBackend, filters.OrderingFilter)
    filter_fields = '__all__'
    search_fields = '__all__'
    ordering_fields = '__all__'
```

**Comment by sergiomb2** [comment]
Based on https://github.com/adamchainz/django-mysql/issues/375 , I made one step forward in https://github.com/carltongibson/django-filter/issues/768#issuecomment-326334166

**Comment by jheld** [comment]
What's the status of this?

**Comment by adamchainz** [comment]
Looking at this again, I think this is a django-filter thing and you should use the snippet in the link to integrate the two libraries. I don't think it's worth shipping a django-filter integration here, as soon the JSONField will be deprecated as it's added to Django Core in (hopefully) 3.1: https://github.com/django/django/pull/12392 .
