### ISSUE TITLE
Allow passing output_field to JSONExtract

### ISSUE THREAD

**Issue by ryselis** [adamchainz/django-mysql#360]
Summary: Currently some JSON field related database functions accept output_field as parameters, but `JSONExtract` always assumes that `JSONField` is needed, even though the value extracted is a flat type value.

Consider this example:
assume we have a model `Document` with `JSONField` `dynamic_data`. Assume the following content of a `Document` instance's `dynamic_data`:
`{
    'title': 'amazing title'
}`

Currently this query is not possible:
`Document.objects.annotate(title=JSONExtract("dynamic_data", "$.title")).filter(title__icontains="amazing")`
because
`NotImplementedError: Lookup 'icontains' doesn't work with JSONField`
since `JSONField` is hardcoded in `JSONExtract`.

I suggest adding `output_field` parameter to `JSONExtract` so that it would be possible to use `icontains` on annotated data.

**Comment by adamchainz** [comment]
I'm not sure if this works in general, as `JSON_EXTRACT` returns an expression of type `json` in MySQL. I think you'd need to `CAST` to `CHAR` as before you could use `LIKE` (what `icontains` maps to).

**Comment by ryselis** [comment]
I have tried it like this:

    class EzJSONExtract(Func):
        function = 'JSON_EXTRACT'

        def __init__(self, expression, *paths, output_field=None):
            from django_mysql.models.fields import JSONField

            exprs = [expression]
            for path in paths:
                if not hasattr(path, 'resolve_expression'):
                    path = Value(path)
                exprs.append(path)
            output_field = output_field or JSONField()
            super().__init__(*exprs, output_field=output_field)

Then
`Document.objects.annotate(title=EzJSONExtract("dynamic_data", "$.title", output_field=CharField())).filter(title__icontains="amazing")` works just fine

**Comment by adamchainz** [comment]
Seems `ez` easy.

Will look into it a bit more before adding.
