### ISSUE TITLE
Support __icontains lookup on JSONField

### ISSUE THREAD

**Issue by sergiomb2** [adamchainz/django-mysql#375]
Summary: NotImplementedError at /api/table/ Lookup 'icontains' doesn't work with JSONField (when try do a searh including one JSONField

Django Version: *Django 1.11.3*

Database and version used: *community-mysql-5.7.18-2.fc25.x86_64*

Version: *django-filter (1.0.4) django-mysql (2.1.0) djangorestframework (3.6.3)*  

**NotImplementedError at /api/table/
Lookup 'icontains' doesn't work with JSONField**

key  | value 
-- | --
Request Method: |	GET
Request URL: 	| http://127.0.0.1:51002/api/table/?search=ICT
Django Version: |	1.11.3
Exception Type: |	NotImplementedError
Exception Value: |	Lookup 'icontains' doesn't work with JSONField
Exception Location:  |	/usr/lib/python3.5/site-packages/django_mysql/models/fields/json.py in get_lookup, line 124
Python Executable: 	| /usr/bin/python3
Python Version: |	3.5.3

like I wrote , should something similar to https://github.com/adamchainz/django-mysql/pull/368 register 
icontains and the SQL is simple like :  

    SELECT * FROM table WHERE json_field COLLATE utf8mb4_unicode_ci LIKE '%ICT%'

**Comment by adamchainz** [comment]
Why do you want to do LIKE on JSON? It's disabled to avoid confusion, it doesn't make sense really since it will not search just the keys or just the values, but the whole JSON string, making it somewhat meaningless.

**Comment by sergiomb2** [comment]
the search function is a search function to search in *all* JSON , but if just search on values is better , but I don't think we got a way to search only on values , so it is better search on all JSON.
What do you mean it is disabled ? how I enable it ? 
Thanks.

**Comment by adamchainz** [comment]
These lines just disable it, as you can see the exception is raised there: https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L117 

You could re-enable it by subclassing and double-`super()`ing around the JSONField code if you want to hack it up.

I think it's better though that you build a custom search function for your code that checks just the keys/values you expect, or use `JSON_SEARCH`. I can see why merging #368 would help, I haven't got around to looking at it properly yet. You should be able to create a Django DB Function that calls `JSON_SEARCH` fairly easily though, lmk how that goes if you try it.

**Comment by sergiomb2** [comment]
yeah icontains looks it works as expect when I remove it from "# Have to 'unregister' some incompatible lookups" , I will dig this further later this week or on next week . 
Thanks for the information .

**Comment by sergiomb2** [comment]
To search in jsonfields with words with accents and insensitive case, we need add COLLATE utf8mb4_unicode_ci  [1] 
[1]

    <field> COLLATE utf8mb4_unicode_ci LIKE '%DATA%'

So this code works was expect (search on keys and on values) : 
```
from django.db.models.lookups import IContains
import django_mysql.models

class JSONIContains(IContains):
    def process_lhs(self, compiler, connection, lhs=None):
        lhs = lhs or self.lhs
        to_add = compiler.compile(lhs)
        to_add = ('%s COLLATE utf8mb4_unicode_ci ' % to_add[0], to_add[1])
        return to_add


class JSONField(django_mysql.models.JSONField):
    def get_lookup(self, lookup_name):
        # Have to 'unregister' some incompatible lookups
        if lookup_name in {
            'range', 'in', 'iexact', 'startswith',
            'istartswith', 'endswith', 'iendswith', 'search', 'regex', 'iregex'
        }:
            raise NotImplementedError(
                "Lookup '{}' doesn't work with JSONField".format(lookup_name)
            )
        return super(Field, self).get_lookup(lookup_name)

JSONField.register_lookup(JSONIContains)
```

**Comment by adamchainz** [comment]
I think your use case is probably a bit esoteric, as searching JSON like this doesn't make much sense in general. If I see more support for this idea I'll reconsider it though.

I'll be adding a `JSONSearch` db function that implements the MySQL `JSON_SEARCH` function, which is probably more generally useful, and can be used to check if any *value* contains a particular string.

**Comment by sergiomb2** [comment]
is better have a search which check json as a text than nothing

**Comment by pjjmd** [comment]
>These lines just disable it, as you can see the exception is raised there: https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L117


I'm trying to get a case insensitve search working for dictionaires stored in jsonfields, i've removed the 'icontains' and iexact from the catch, so they don't throw exceptions, but the result is still a case sensitive search. Is there something simple i'm missing?

**Comment by adamchainz** [comment]
The JSON type is always `utf8mb4_bin`, and:

> Because utf8mb4_bin is a binary collation, comparison of JSON values is case sensitive.

https://dev.mysql.com/doc/refman/5.7/en/json.html

You could fix this by wrapping with `CAST(column AS CHAR)`, but that means re-implementing `__icontains` with a new lookup. For example:

```
chainz@localhost [14]> create table t (c json);
Query OK, 0 rows affected (0.03 sec)

chainz@localhost [15]> insert into t (c) values ('"test"');
Query OK, 1 row affected (0.00 sec)

chainz@localhost [16]> select * from t where c like '%tesT%';
Empty set (0.00 sec)

chainz@localhost [17]> select * from t where cast(c as char) like '%tesT%';
+--------+
| c      |
+--------+
| "test" |
+--------+
1 row in set (0.00 sec)
```

Sorry I don't have time to do this right now but since there's clearly interest in using `LIKE` on JSON fields I'd accept a PR

**Comment by sergiomb2** [comment]
on operator LIKE , I append "COLLATE utf8mb4_unicode_ci" is the hack that make it work .
 
    where.append("%s COLLATE utf8mb4_unicode_ci LIKE %%s" % sql_fld)

or 

    where=['data->>"$.NAME" COLLATE utf8mb4_unicode_ci LIKE %s']

**Comment by adamchainz** [comment]
Ah yes, I think that's basically an implicit CAST
