### ISSUE TITLE
Ordering Searches by JSON Field Contents

### ISSUE THREAD

**Issue by pjjmd** [adamchainz/django-mysql#383]
I know this is a bit of a shaky field when it comes to the ORM, but the example given in the exposition is super unclear. https://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html#ordering-lookups describes an attr field that seems more like an array then a JSON object.

**Comment by adamchainz** [comment]
MySQL JSON can store *any valid JSON* and is thus not restricted to JSON objects. See at the top:

> A field for storing JSON. The Python data type may be either str (unicode on Python 2), int, float, dict, or list - basically anything that is supported by json.dumps. There is no restriction between these types - this may be surprising if you expect it to just store JSON objects/dicts.

**Comment by adamchainz** [comment]
Also the example in the exposition is not what you linked to? I think the ordering lookups is clear enough, it does say to go check the MySQL docs for clarification.

**Comment by pjjmd** [comment]
> this may be surprising if you expect it to just store json objects/dicts

It was in fact surprising! Sorry to bother you!

**Comment by adamchainz** [comment]
np glad to help

**Comment by sergiomb2** [comment]
I use this snippet 

            order_by = None
            if json_order is not None:
                order_by = []
                order_by_pre = json_order.split(',')
                for item in order_by_pre:
                    first = ""
                    if item[0] == '-':
                        first = item[0]
                        item = item[1:]
                    if item.startswith("data."):
                        newitem = 'ci.data->"$.%s"' % item[5:]
                    else:
                        newitem = item
                    order_by.append("%s%s" % (first, newitem))
                #order_by = ['ci.data->"$.AREA"', '-ci.data->"$.NAME"']
            return Ci.objects.extra(where=query, params=params, order_by=order_by)

To work we need table name in query ! (with the '.' ) because in line 311 of django/db/models/sql/compiler.py  we got:

            if '.' in field:
                # This came in through an extra(order_by=...) addition. Pass it
                # on verbatim.
                table, col = col.split('.', 1)
                order_by.append((
                    OrderBy(
                        RawSQL('%s.%s' % (self.quote_name_unless_alias(table), col), []),
                        descending=descending
                    ), False))
                continue

and works very well

**Comment by adamchainz** [comment]
@sergiomb2 there's no need for that, just use `order_by(JSONExtract('attrs', '$.AREA'))`
