### ISSUE TITLE
subprocess imports (PIPE, Popen, etc).

### ISSUE THREAD

**Issue by kjam** [adamchainz/django-mysql#396]
Summary: Subprocess imports throw an error on some architectures

Django Version: Django 1.11.1
Database and version used: CloudSQL MySQL 5.7
Version: Django-MySQL 2.1.0
Python version: 2.7 (GoogleAppEngine)

When deploying on certain cloud architectures (here Google App Engine), the valid way to use subprocess is to do a global import:

`import subprocess`

And then later utilize the imported namespace:

`subprocess.PIPE`

I am happy to send a patch if this is useful for you. For now I have modified my deployed code as a workaround. Thanks for creating a useful library!

**Comment by adamchainz** [comment]
Yes please make a PR :)

That's pretty evil of them to break the namespace like that. Have you got a docs link?

**Comment by kjam** [comment]
Ya, took a lot of head scratching to figure out. There is no documentation about it per se. Just a lot of StackOverflow questions like this one: https://stackoverflow.com/questions/40489794/importerror-cannot-import-name-popen-google-app-engine-deployment-error  :disappointed: 

I'll send a PR later today. Thanks again for a really neat library! :smile:
