### ISSUE TITLE
Filter on JSONField array

### ISSUE THREAD

**Issue by quytang** [adamchainz/django-mysql#401]
I have a book model

    class Book():
      ...
      tags: JSONField()

I have some records:

    Book(..., tags: ['TECH', 'BUSINESS'])
    Book(..., tags: ['MARKETING'])

I want to filter out the books those have tag 'Tech' or 'Business'
    

    query = Q (
        Q(tags__contains='Tech') |
        Q(tags__contains='Business')
    )

I've tried to used contains, contained_by, has_key, has_any_keys but got no luck.
The result is always empty.

Update
==========

It was my mistake!
I found the problem, JSONField is case sensitive.

The value save in DB was `["TECH", "BUSINESS"]` instead of `["Tech", "Business"]`.

Now the question turns out 'How to search it with case insensitive?'

**Comment by adamchainz** [comment]
`has_key`/`has_any_keys` are for *JSON objects* which are python `dict`s. You're using *JSON Arrays* which are `list`s.

`contains` will work but you need to pass lists/arrays - see the MySQL docs: https://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html#containment-lookups

**Comment by quytang** [comment]
@adamchainz  `icontains` doesn't work. It throws the error `Lookup 'icontains' doesn't work with JSONField`
But I want the tag to be case insensitive in filters. Are there any way to achieve that.
Thanks

**Comment by adamchainz** [comment]
I'm afraid it's not easy to do, it needs some more work in SQL.

**Comment by adamchainz** [comment]
Also asked on SO: https://stackoverflow.com/questions/46974300/filter-on-jsonfield-array

I've looked a bit more and can't find any appropriate SQL to get around the case-sensitivity of the JSON data type ( https://dev.mysql.com/doc/refman/5.7/en/json.html ) whilst still using `JSON_CONTAINS`. I think however you cast it, it gets converted back to the binary, case-sensitive collation before comparison in `JSON_CONTAINS`:

```sql
chainz@localhost [20]> select json_contains('["A"]', '"a"') as test;
+------+
| test |
+------+
|    0 |
+------+
1 row in set (0.00 sec)

chainz@localhost [21]> select json_contains('["A"]' collate utf8_unicode_ci, '"a"') as test;
+------+
| test |
+------+
|    0 |
+------+
1 row in set (0.00 sec)

chainz@localhost [22]> select json_contains(cast('["A"]' as char character set utf8mb4) collate utf8mb4_unicode_ci, '"a"') as test;
+------+
| test |
+------+
|    0 |
+------+
1 row in set (0.00 sec)
```

I'm afraid it just can't be done (unless I'm missing something). You can ofc fix this by storing the tags in their own table in a more relational manner, where MySQL string comparison defaults to case-insensitive.
