### ISSUE TITLE
Disable remote database system check

### ISSUE THREAD

**Issue by sonirico** [adamchainz/django-mysql#432]
I have a local MySQL 5.7 database and a remote database under version 5.6. I would like to have system checks enabled for the former but disabled for the latter. Any good approach?

**Comment by adamchainz** [comment]
Are you seeing errors, or just trying to avoid connecting to the remote database when starting the app?

Also Django itself contains system checks that connect to each of your database connections, so it's not unique to django-mysql.

**Comment by adamchainz** [comment]
( e.g. W002 in https://docs.djangoproject.com/en/2.0/ref/checks/#database )

**Comment by sonirico** [comment]
Sorry in advance for the delayed feedback. The thing is that the second database is remote (nothing to do here) and runs 5.6. For some embarrasing reasons, the app I have to manage is deployed with the runserver comand, running system checks. So, the remote one does no allow JSONFields at all, so I had to silence the `django_mysql.E016 ` system check, and now it works.

Thats the fastest approach to get things to work, but I would really like to have that system check enabled for the local DB. Looking at https://github.com/adamchainz/django-mysql/blob/95eb4cecf4d50b1afa5c60030d2f01d622215b18/django_mysql/checks.py#L88
we can see that all databases  are being checked. I wonder that if we could somehow enable a flag in the `DATABASE` django setting to prevents checks to be run on a single DB.

**Comment by adamchainz** [comment]
But the check is just to see if *at least one* of your connections is 5.6+, and since you say that is the case, it should be fine: https://github.com/adamchainz/django-mysql/blob/95eb4cecf4d50b1afa5c60030d2f01d622215b18/django_mysql/models/fields/json.py#L58

**Comment by sonirico** [comment]
Ok, I have just dumped a little into locally installed source. Turns out that version 2.2.0 do improve JSON field checks ;)

**Comment by adamchainz** [comment]
New issue template asks you to report versions: https://github.com/adamchainz/django-mysql/blob/master/.github/ISSUE_TEMPLATE.md

Next time please fill it in!

But at least this got me to write #434
