### ISSUE TITLE
Docs on checks does not specify how to change SQL_MODE 

### ISSUE THREAD

**Issue by amirulabu** [adamchainz/django-mysql#441]
Summary: In the docs [here](http://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w001-strict-mode) it did not specify on how to change SQL_MODE. I want to contribute extending the checks section on how to view and edit SQL_MODE. This will be beneficial for user that is not familiar with setting up mysql/mariadb.

**Comment by adamchainz** [comment]
What about this paragraph, which comes with an accompanying change to the settings file?

> The easiest way to change sql_mode for your app is to set it from the init_command that is run on each new connection by MySQLdb: ...

I think that's pretty clear.

**Comment by amirulabu** [comment]
I have tried that, but it does not work. I have to set sql_mode from mysql command-line

**Comment by adamchainz** [comment]
I think also the following paragraph covers that too:

> You can change sql_mode permanently by using SET GLOBAL from an admin user on the server, plus changing your configuration files so the setting survives a server restart. For more information, see Using System Variables system variables in the MySQL documentation.

Closing this because I consider it adequate.
