### ISSUE TITLE
Test on MySQL 8

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#453]
It's GA now https://mysqlserverteam.com/whats-new-in-mysql-8-0-generally-available/

**Comment by Normos** [comment]
Will take a look at it.

**Comment by Normos** [comment]
@jwhitlock I could take a look on Friday if that alright with you.

**Comment by sudarshandk** [comment]
The document doesn't mention the support for MySQL 8. Is it supported now?

**Comment by adamchainz** [comment]
It's still not officially supported, #583 will add that.
