### ISSUE TITLE
Extend JSONField to use custom encoder/decoder

### ISSUE THREAD

**Issue by Naitreey** [adamchainz/django-mysql#461]
Summary: How about letting user choose JSON encoder/decoder to use for `JSONField`?

I'm thinking about whether it is feasible and preferable for user to be able to supply a custom JSON encoder (such as `DjangoJSONEncoder`) on `JSONField` initialization like this:

```python
class JSONField(Field):
    encoder = json.JSONEncoder
    decoder = json.JSONDecoder

    def __init__(self, encoder=None, decoder=None, *args, **kwargs):
        self.encoder = encoder or self.encoder
        self.decoder = decoder or self.decoder
        # ...
```

In this way, it's possible to reduce duplicated code on upper layers that has to coerce different
types of values to/from JSON-serializable form.

I'm not sure whether it will potentially break anything cooperating with current `JSONField` such as
JSON functions, as I currently don't have time digging into the code. So I'll just put my two cents here (sorry).

**Comment by adamchainz** [comment]
Yeah I think this could work. Will look into it at the Djangocon EU sprints this weekend.

**Comment by Naitreey** [comment]
@adamchainz That's great, thanks.

**Comment by adamchainz** [comment]
Merged, will be out in next release!
