### ISSUE TITLE
Add Mathematical Functions

### ISSUE THREAD

**Issue by denisiko** [adamchainz/django-mysql#482]
# Summary

There are already some numeric functions provided, like `Abs()`, `Ceiling()` and `Round()`. A lot of MySQL's mathematical functions are missing though, like `POW()` or `RADIANS()` (see [list of MySQL's mathematical functions](https://dev.mysql.com/doc/refman/5.7/en/mathematical-functions.html)).

Would be nice to have them inside functions.py so you could easily import them instead of defining them for yourself. Although there is already a [Django PR](https://github.com/django/django/pull/9622) for this, it doesn't seem to be pushed soon.

# Configuration

Django Version: Django 2.0.0

Database and version used: MySQL 5.7

Version: Django-MySQL 2.2.2

**Comment by adamchainz** [comment]
I'd rather focus on Django core for things like this, I don't want to cause unnecessary fracturing here. Things like POW and other pure maths can always be emulated on DB's that don't have dedicated functions.

**Comment by denisiko** [comment]
OK. But then, why is there a function like `Abs()` in the 1st place? Shouldn't it also come only from the core or be constructed by the user itself?

**Comment by adamchainz** [comment]
I wasn't thinking when I made it, I should have pushed it in core despite it being harder :) I will probably deprecate it here.

**Comment by denisiko** [comment]
OK

**Comment by carltongibson** [comment]
There's a couple of open PRs on Django adding DB functions (e.g. https://github.com/django/django/pull/9543 https://github.com/django/django/pull/9622). They look nearly complete. They probably just need picking up, polishing and advocating. (In case anyone here has capacity. 🙂)
