### ISSUE TITLE
dangling connection created during system check may become unusable

### ISSUE THREAD

**Issue by Naitreey** [adamchainz/django-mysql#485]
*Summary*: mysql connection created during system check is not closed timely. This connection might (mysteriously) become unusable afterwards (for reason I could not fully understand for now), which blocks the database access in application logic.

*Description*: I'm using django with celery. Today I noticed that any task that accesses database by Django ORM just hangs forever (i.e. they only start but never finish). After some digging I realized it's database connection that blocks forever and never comes back.

After another really painful debugging process, I figured out that, during django's system checking process, django-mysql created a persistent database connection rather than a temporary one, thus get re-used in application code. But somehow its connection is dropped, which causes any code that implicitly depends on it blocks forever.

Specifically, I think the following code in `django_mysql/checks.py` should use a `BaseDatabaseWrapper.temporary_connection()`, therefore ensure connection is closed cleanly afterwards.

```python
def check_variables(app_configs, **kwargs):
    errors = []

    for alias, connection in mysql_connections():
        with connection.cursor() as cursor: # connection.temporary_connection()
            cursor.execute("""SELECT @@sql_mode,
                                     @@innodb_strict_mode,
                                     @@character_set_connection""")
            # ...
```

(Sorry if this poor bug report seems in a hurry, I'm really tired (it's 4 AM my brain isn't working...) )

*Django Version*: Django 2.0.6

*Database and version used*: mysqld  Ver 5.7.22 for Linux on x86_64 (MySQL Community Server (GPL))

*Version*: Django-MySQL 2.2.2

**Comment by adamchainz** [comment]
Temporary connection sounds good to me - you want to make the PR and get the GitHub poitns since you've been to all this effort?

**Comment by Naitreey** [comment]
Hi, @adamchainz  PR #486 is opened for this.
