### ISSUE TITLE
Not  working  (/*QueryRewrite':SQL_CACHE*/1) query  hint

### ISSUE THREAD

**Issue by ismt** [adamchainz/django-mysql#498]
Hello
  
Summary:
This query take no effect,  mysql  variable  Qcache_queries_in_cache  not  changed  (i  restarted  mariadb  before  test  )
```mysql
SELECT * FROM test WHERE ((/*QueryRewrite':SQL_CACHE*/1) AND id=1 )
```
but  this  works,  Qcache_queries_in_cache  increased  by  one  
```mysql
SELECT SQL_CACHE * FROM test WHERE id=1
```
I don't know if this is a bug, but obviously query hints doesn't work

mysql  config  

> query_cache_size=50M
> query_cache_limit=50K
> query_cache_type=DEMAND

Hints  enabled  from  example  

```python3
from mythings import MyBaseModel
from django_mysql.models import QuerySet

class MySuperDuperModel(MyBaseModel):
    objects = QuerySet.as_manager()
```
Django Version: 1.11.15

Database and version used: MariaDB 10.1.33

Version:  2.4.0

example  table  in  attach  [t.zip](https://github.com/adamchainz/django-mysql/files/2277801/t.zip)

**Comment by adamchainz** [comment]
The query `SELECT * FROM test WHERE ((/*QueryRewrite':SQL_CACHE*/1) AND id=1 )` should be rewritten. Is `django_mysql` in your `INSTALLED_APPS` as per [the installation guide](https://django-mysql.readthedocs.io/en/latest/installation.html) and did you set `DJANGO_MYSQL_REWRITE_QUERIES = True` in your settings as per [query hints](https://django-mysql.readthedocs.io/en/latest/queryset_extensions.html#query-hints) ?

Also the query cache is removed in MySQL 8 and is disabled by default in MariaDB ([docs](https://mariadb.com/kb/en/library/query-cache/)), so I'd recommend against building a new app that depends on it at this time - instead maybe try Django's cache framework. You can avoid running memcached by using Django-MySQL's [cache backend](https://django-mysql.readthedocs.io/en/latest/cache.html).

**Comment by ismt** [comment]
Very  sorry,  i  not  add  django_mysql in INSTALLED_APPS

I thought without this will not work and did not look in the settings, only enable 
 DJANGO_MYSQL_REWRITE_QUERIES

I  test  with  correct  settings  and  this  works

Problem  resolved

Thanks  for  info  about  query  cache  in  mysql  8

**Comment by adamchainz** [comment]
👌Excellent
