### ISSUE TITLE
Support INSERT ... ON DUPLICATE KEY UPDATE ...

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#501]
MySQL's `INSERT ... ON DUPLICATE KEY UPDATE ...` is really useful for quickly doing upserts of big batches of data. We could support an interface like `Model.objects.bulk_create` to do a `bulk_upsert`. Django has discussed adding this for some time but differences in all the DB's syntaxes and methods have slowed it.

One caveat is that it shouldn't be done if there is >1 unique index on the table. This can be checked for with:

```
SELECT
    COUNT(*)
FROM INFORMATION_SCHEMA.STATISTICS
WHERE
    TABLE_SCHEMA = %s AND
    TABLE_NAME = %s AND
    NON_UNIQUE = 0
```

... and the respective parameters.

Perhaps a model/manager class mixin should be used to supply the `bulk_upsert` method, which can add a `check()` method to enforce this constraint.

Docs: https://mariadb.com/kb/en/library/insert-on-duplicate-key-update/

**Comment by violuke** [comment]
This would be great if support could be added :+1:

**Comment by adamchainz** [comment]
Django has an open ticket and PR: https://github.com/django/django/pull/13065

Therefore Django-MySQL won't be implementing this.
