### ISSUE TITLE
For ListTextField no ForeignKey can be used for the base field?

### ISSUE THREAD

**Issue by eliUni** [adamchainz/django-mysql#505]
Hi,

I would like to define a ListTextField based on a foreign key. The foreign key is a CharField.
But I receive the following error:

**Base field for list must be a CharField or IntegerField.**

Django Version: Django==1.11.10

Database and version used: mysql  Ver 14.14 Distrib 5.7.21, for Win64 (x86_64)

Version: django-mysql==2.3.1

**Comment by adamchainz** [comment]
I'm afraid not, because referential integrity can't be guaranteed. The restriction to use only `CharField` or `IntegerField` as the base field can't be removed.

Also I'd recommend you don't use `ListTextField` but `JSONField` instead if you can.
