### ISSUE TITLE
Update documentation on Lock

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#507]
Summary: Multiple locks are supported on MySQL 5.7 and MariaDB 10.0+. Also MariaDB at least made it re-entrant, and supports microseconds on timeout.

**Comment by HuffAndPuff** [comment]
Also, taken from https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html

> MySQL 5.7 and later enforces a maximum length on lock names of 64 characters. Previously, no limit was enforced.

**Comment by adamchainz** [comment]
@HuffAndPuff updated in #627 !
