### ISSUE TITLE
Error with JSONField and mysql-connector 

### ISSUE THREAD

**Issue by ebertti** [adamchainz/django-mysql#524]
model code:
```python
class MyModel(models.Model):
    name = models.CharField(max_length=35)
    data_json = JSONField()

```

**makemigrations** output

````python

migrations.CreateModel(
    name='MyModel',
    fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=35)),
        ('data_json', JSONField(default=dict)),
])
````

Error on running **migrate**

```bash

django.db.utils.ProgrammingError: BLOB, TEXT, GEOMETRY or JSON column 'data_json' can't have a default value

```

* Django Version: *Django 2.1.2*
* Database and version used: *MySQL 5.7*
* MySQL driver: *mysql-connector-python==8.0.13*
* Version: *Django-MySQL==2.4.1*

**Comment by adamchainz** [comment]
Django doesn't support `mysql-connector-python`, so I'm afraid this library doesn't either. How did you even get it working?

**Comment by adamchainz** [comment]
Btw I have a plan to get Django to support `pymysql`, which I have done unofficially on a few projects and it's worked fine (being a drop-in replacement for `mysqlclient` ex. `MySQLdb`)

**Comment by ebertti** [comment]
in fact, it is working. And very well.

I change from mysqlclient because the main developer don't want to make wheels for mac, windows and another dist of linux, so is very hard to install on mac os, every update is very hard to maintain.

Mysql-connector now have bind of C, and get near benchmarks of mysqlclient. I gonna make a Medium article explain this change in a few days.

Mysql-connector make they own backend to working with Django.

https://dev.mysql.com/doc/connector-python/en/connector-python-django-backend.html

Just need to do this:

`pip install mysql-connector-python`

``` python
DATABASES = {
    'default': {
        'NAME': 'user_data',
        'ENGINE': 'mysql.connector.django',
        'USER': 'mysql_user',
        'PASSWORD': 'password',
   }
}
```
Is working fine for me. I recommend you to try it.

Indeed: Mysql > 5.7 does not support default value for a json field 

https://dev.mysql.com/doc/refman/5.7/en/json.html

> A JSON column cannot have a default value.

My work arround was:

`data_json = JSONField(default=None)`

But I think you need to make a different approach on this line:

https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/json.py#L31

Or:

You can not propagate this on create tables and only work on python code when this field is not used on new objects.

**Comment by adamchainz** [comment]
I don't have problems installing `mysqlclient` on mac, as long as I do `brew install mariadb` or `brew install mysql` first to get the dev library.

I don't have the energy to look into supporting `mysql-connector-python`. Django doesn't support it officially and generally Oracle aren't very helpful. I use MariaDB for all my projects these days, will get official Django support for that soon.

Django's field defaults are not database level defaults, they actually only exist in the python layer. I would guess the `mysql-connector-python` Django backend is doing something different around this, and the fault is *really* there. Django DB backends have a private API that changes from Django release to release, they're really quite complicated to write and keep correct between versions, and I don't see any documentation from Oracle which versions of Django are supported. When I look at the source code that's on PyPI in the tarball download, I see it has references to Django 1.7 and 1.8 but no higher versions, so I wouldn't be surprised if it's not really tested with Django 1.8+

**Comment by adamchainz** [comment]
Closing due to age.
