### ISSUE TITLE
InterfaceError: (2003, "2003: Can't connect to MySQL server)

### ISSUE THREAD

**Issue by dhaval-mehta** [adamchainz/django-mysql#531]
Summary: frequently I got error: InterfaceError: (2003, "2003: Can't connect to MySQL server on '[HOST]:3306' (-3 Temporary failure in name resolution)", None). Within few seconds entire system starts working normally automatically. 

Django Version: 2.0.5

Database and version used: MySQL 5.7.23-log

Version: 2.2.2

**Comment by adamchainz** [comment]
Hey, I don't think this is a problem with Django-MySQL, but with Django core, `mysqlclient`, your MySQL server, or *most likely* your network. Searching online finds me plenty of related answers: https://duckduckgo.com/?q=mysql+Temporary+failure+in+name+resolution&ia=web . Afaiu the error message is that DNS resolution failing somewhere, and is not to do with Django-MySQL.
