### ISSUE TITLE
Officially support Django 2.2

### ISSUE THREAD

**Issue by pmontepagano** [adamchainz/django-mysql#543]
Summary: Django 2.2 (LTS) is out and the docs don't mention if it is supported or not.

**Comment by adamchainz** [comment]
It's not supported. I have a plan to work on it, and all my other Django projects. It's normally a big undertaking for Django-MySQL since so many bits use the internals of Django.

**Comment by adamchainz** [comment]
Django 2.2 and 3.0 are supported.
