### ISSUE TITLE
Migrations fail on Django 2 while using Mysql 8 with JSONField

### ISSUE THREAD

**Issue by hgarcia101685** [adamchainz/django-mysql#602]
Django 2.2.4

MYSQL 8.0.18

django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'jsonb NOT NULL, `last_sold` datetime(6) NOT NULL, `created_at` datetime(6) NOT N' at line 1

**Comment by adamchainz** [comment]
`jsonb` is the data type name in PostgreSQL, this implies you're using `django.contrib.postgres`'s JSONField, not Django-MySQL's.
