### ISSUE TITLE
Importing ABC directly from collections was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [adamchainz/django-mysql#606]
https://github.com/adamchainz/django-mysql/blob/bc4ff381d3a61af6dc448312205c2c19d9c5f97e/src/django_mysql/models/lookups.py#L126

**Comment by adamchainz** [comment]
Thanks, though it sems this will actually be deferred: https://mail.python.org/archives/list/python-dev@python.org/thread/EYLXCGGJOUMZSE5X35ILW3UNTJM3MCRE/

**Comment by tirkarthi** [comment]
It will eventually be done in one cycle or another. Given that the change itself is small with this project supporting only Python 3. I would suggest fixing this since it's already deprecated since 3.4 .
