### ISSUE TITLE
Faster TransactionTestCase

### ISSUE THREAD

**Issue by jonatron** [adamchainz/django-mysql#610]
I had an issue where `TransactionTestCase` was very slow with MySQL. Upon profiling, I found that `TRUNCATE`ing all tables was taking a significant amount of time. I wrote a `TransactionTestCase` SubClass to only `TRUNCATE` tables that aren't empty. Would you like a Pull Request for this?

**Comment by adamchainz** [comment]
Sure, if you’re willing to add docs too!
