### ISSUE TITLE
Why Don't You Support Django help_text  -> Mysql comments?

### ISSUE THREAD

**Issue by KimSoungRyoul** [adamchainz/django-mysql#628]
### as is 
~~~Python
class AModel(models.Model):
"""
this is doc string
"""
     a_field = models.CharField(help_text="this is help text", max_length=32, null=False)
~~~
-> `python manage.py makemigrations`
~~~Python
migrations.CreateModel(
            name="AModel",
           help_text="this is doc string",
            fields=[
                ("a_field", models.CharField(max_length=32, help_text="this is help text") ),
            ]
)
~~~

-> `python manage.py migrate`
~~~SQL
create table a_model
(
     a_field varchar(32) not null COMMENT 'this is help text',
) comment 'this is doc string';
~~~

**Comment by adamchainz** [comment]
This would need a change in Django itself. I wouldn't be in favour of the docstring or help_text being automatically copied, instead they should be explicit extra fields. You can bring this up on the django-developers mailing list if you want, with an explanation of your use case. You can alreayd achieve this with `RunSQL` in yoru own migrations.

**Comment by KimSoungRyoul** [comment]
Thank You For Your Opinion
