### ISSUE TITLE
Suggestion : SQL alter after column. 

### ISSUE THREAD

**Issue by KimSoungRyoul** [adamchainz/django-mysql#629]
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

Hello I need to use SQL:`after {column}`

Like a
`
ALTER TABLE aaa_model MODIFY COLUMN `bbb` varchar(32) default 'sdf' not null after aaa ;
`

#### if i develop this feature , Are you willing to review my code? 
I want to hear your thought.

Thank you

p.s. Thanks to you, I'm always using django-mysql  well.

**Comment by adamchainz** [comment]
Hi @KimSoungRyoul 

This is a generic SQL feature supported on multiple databases. I think if we were to add it, it would be in Django core. I can imagine it's possible with an extra parameter to the `AddField` migration operation which `SchemaEditor.add_field` would use to insert an `AFTER` clause. Similar for `AlterField`.

Adding columns out of order is something that's *bad* for scale though. MariaDB's "instant ADD COLUMN" feature only works if you are adding columns at the end. If you try add an AFTER or BEFORE clause, it will use the slow ADD COLUMN method, which can block your database until done. I'm not sure about MySQL at this point, but its docs don't mention it either way.

Would you mind discussing this on the django-developers mailing list? And would you mind explaining a bit more why you need this?

Thanks,

Adam

**Comment by KimSoungRyoul** [comment]
it's issue between DBAs(DatabaseAdmin) to Developers 

DBAs want to sort column by dataType 
like a
~~~SQL
aaa_str : varchar(32)
bbb_str : varchar(32)
ccc_str : varchar(32)

aaa_date: datetime
bbb_date: datetime
ccc_date: datetime
~~~

But Developer want to sort Field by business
like a 
~~~Python
aaa_str : CharField(max_length=32)
aaa_date: DateTimeField()

bbb_str : CharField(max_length=32)
bbb_date: DateTimeField()

ccc_str : CharField(max_length=32)
ccc_date: DateTimeField()
~~~~


but django migration does not support MySQL `After column`

also 

Developers were unsatisfactory  customize migrationFiles by hand EveryTime

There's only one way  i can do , create new feature

`I think if we were to add it, it would be in Django core.`
thank you for your comment 


and by the way.
https://github.com/adamchainz/django-mysql/issues/628
this issue was existed on django issue community
https://code.djangoproject.com/ticket/18468
so i assigned to me
