### ISSUE TITLE
Move query rewriting to database instrumentation

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-mysql#644]
Summary: Rather than monkeypatching `CursorWrapper.execute`, use [database instrumentation](https://docs.djangoproject.com/en/3.0/topics/db/instrumentation/) to install the hook.

The setting can then always install it with the same technique as https://github.com/scoutapp/scout_apm_python/blob/639b7ac6a6a859e17db5c2e6b4d6ce2366ddd7a4/src/scout_apm/django/instruments/sql.py#L71 . And users can optionally install it only for certain code paths by installing it using `with connection.execute_wrapper(rewrite_queries):` (would need documenting).

**Comment by jheld** [comment]
Thank you! I will discuss this with my team next week to see if we can open a PR for this change here.

I had totally forgotten about the django instrumentation tooling -- excellent suggestion!
