### ISSUE TITLE
Document how to use the extension with a custom Manager and custom QuerySet

### ISSUE THREAD

**Issue by gabn88** [adamchainz/django-mysql#649]
I have a custom Manager (based on models.Manager) and a custom QuerySet (based on models.QuerySet). 

It is all setup like explained on the official docs: https://docs.djangoproject.com/en/3.0/topics/db/managers/#custom-managers

When I add the QuerySetMixin on the QuerySet, I get 

`AttributeError: '.... Manager'  object has no attribute 'use_index'.

What is the easiest way to add all methods to the Manager without manually typing them?

**Comment by adamchainz** [comment]
Did you see https://docs.djangoproject.com/en/3.0/topics/db/managers/#from-queryset ?

**Comment by gabn88** [comment]
Oh wow! Have been working for over 5 years on Django projects and never saw it. Always manually copy-pasted/create the methods on the Manager. It must be new since Django 1.8! 

Thanks for learning me something new!

**Comment by adamchainz** [comment]
Cool. I added some docs in #650.
