### ISSUE TITLE
Raise Exception with non-supported lookups

### ISSUE THREAD

**Issue by gtalarico** [adamchainz/django-mysql#652]
Summary: Should Raise error if unknown lookup is provided.

I understand some lookups are not provided.
However, it's hard to tell which ones are supported. 
Furthermore, attempting to use non-registered lookups also fail silently.
See below - 

```python
# works
ModelWithJsonField.objects.filter(jsonvalue=1)
ModelWithJsonField.objects.filter(jsonvalue__gt=1)

# Raises exception, as expected
ModelWithJsonField.objects.filter(jsonvalue__icontains=1)

# Returns Empty Query set - ie fails silently
ModelWithJsonField.objects.filter(jsonvalue__contains=1)
ModelWithJsonField.objects.filter(jsonvalue__xxx=1)
```

#### Versions
Django==2.2
django-mysql==3.3.0

Thank you for your work on this!

**Comment by adamchainz** [comment]
Those lookups *are* "supported", in that they map to:

* `contains` - JSON array contains - https://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html#containment-lookups
* `xxx` - a path of key 'xxx' is equal to - https://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html#key-index-and-path-lookups

These are the same as django.contrib.postgres' JSONField lookups, which will be part of the universal JSONField from https://github.com/django/django/pull/12392 

Thanks!

**Comment by gtalarico** [comment]
Ah thanks for the clarification. Makes perfect sense now.
