### ISSUE TITLE
Make django's QuerySet.update().order_by('') work for MySQL

### ISSUE THREAD

**Issue by gabn88** [adamchainz/django-mysql#654]
Summary: Since MySQL does not support a defered unique constraint (like some other databases do), it would be great if this package could supply a way to update with an order_by clause. [More here](https://dev.mysql.com/doc/refman/5.7/en/update.html). For example the 

`UPDATE t SET id = id + 1 ORDER BY id DESC;`

example from the MySQL docs is currently not working with Django 2.2 and still gives an IntegrityError for the unique key. 

The query that is executed is:
```
query = 'UPDATE `model` SET `integerfield` = (`model`.`integerfield` + %s) WHERE (`model`.`date` = %s AND `model`.`integerfield` >= %s)'
args = (1, '2020-04-26',  2)
```
As you can see the ORDER_BY, which should make it work, is omitted in the query, while it is in the Django code:

```
                qs_to_increase = self.get_indexing_queryset().filter(
                    integerfield__gte=self.integerfield).order_by('-integerfield')

                # apply changes after getting the qs!
                qs_to_increase.update(integerfield=F('integerfield') + 1)

```
Django Version: Django 2.2

Database and version used: MySQL 8.0.20-0ubuntu0.19.10.1

**Comment by adamchainz** [comment]
That seems more like an issue for Django itself. I'm not sure we can provide an extension here easily, and it would benefit more users there. Would you mind opening this as ticket there instead? Please CC me@adamj.eu.

An easy way to apply a workaround right now with current Django would be a [database instrumentation hook](https://docs.djangoproject.com/en/3.0/topics/db/instrumentation/) applied during your `.update()` that appends the `ORDER BY` clause you want.

**Comment by gabn88** [comment]
https://code.djangoproject.com/ticket/31573#ticket

**Comment by gabn88** [comment]
Sorry, I tried to add you as CC but I couldn't get it to work the way I wanted. Above is the link to the (accepted) ticket.

**Comment by gabn88** [comment]
How would this database instrumentation hook look like?

```
def order_by(execute, sql, params, many, context):
    sql + ' ORDER BY ModelName.table'

with connection.execute_wrapper(order_by):
    do_queries()
```
Or something like that?

**Comment by adamchainz** [comment]
Thanks for the ticket, I've CC'd myself and added a reply.

Your instrumentation looks about right. You don't need the table name per se, and should use `+=` to actually mutate the local SQL variable: `sql += ' ORDER BY column_name'`.

**Comment by gabn88** [comment]
Thank you so much! I have implemented it this way and it works like a charm!

**Comment by gabn88** [comment]
I just wanted to follow up on this, since upgrading to Django 3.1 breaks this way of solving it.

It is because of this commit (I believe):
https://github.com/django/django/commit/a19505eb2ecd4a07ff39f3f66898e68b69d0e680#diff-dabf20e4ab58ae26d868833eefa64d93896519623d676bdb47bee47b0b6b5543 
Before performing the database execution a simple "SELECT VERSION()" is issued if the connection is newly initiated. If you apply the  database instrumentation hook, it will fail for not finding the table.
