### ISSUE TITLE
Support  ON UPDATE CURRENT_TIMESTAMP ( what I'll to make improvement) #674

### ISSUE THREAD

**Issue by KimSoungRyoul** [adamchainz/django-mysql#671]
Hi 
I want to use these Feature with Django
https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

---

### To be
~~~Python
class Abc(models.Model):
    name = models.CharField(max_length=32)
    modified_at = models.DateTimeField(auto_now=True)

~~~
if i execuete below Queryset 
~~~Python
Abc.object.filter(id=1).update(name="qwer")
~~~
`modified_at`Field Does Not be updated 

---

### As Is

Mysql Support these Feature with DDL 
https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

##### if you don't mind  , can I suggest  create DateTimeField with `on_update_current_timestamp` option   ?
~~~Python
from django_mysql import models as mysql_models

class Abc(models.Model):
    name = models.CharField(max_length=32)
    modified_at = mysql_models.DateTimeField(
                          auto_now_add=True, 
                          on_update_current_timestamp=True # new param "on_update_current_timestamp"
                  ) 

~~~

when `on_update_current_timestamp` is True, 
DDL will be generated like a
~~~SQL
create table pratice_111_db.hello11_asdf
(
    name varchar(32) not null,
    a_datetime datetime(6) not null ON UPDATE CURRENT_TIMESTAMP, # `on_update_current_timestamp=True
    id         int auto_increment
        primary key
);
~~~

---

**Comment by adamchainz** [comment]
I don't have time to write something here but you should be able to customize `DateTimeField` to do that. I'd be interested if you had an implementation.

**Comment by KimSoungRyoul** [comment]
https://github.com/adamchainz/django-mysql/pull/674
