### ISSUE TITLE
Using DJANGO_MYSQL_REWRITE_QUERIES in combination with django CACHALOT breaks invalidation

### ISSUE THREAD

**Issue by gabn88** [adamchainz/django-mysql#672]
I really like to use django CACHALOT for a part of the website. It gave a big overall speedup.

But when I combine django CACHALOT with django-mysql, queries which trigger a query rewrite are not invalidated correctly. (for example when using "use_index").

Is there any workaround for this?

**Comment by adamchainz** [comment]
I have never heard of cachalot. Please give more details.

**Comment by gabn88** [comment]
This is the package I'm talking about: https://github.com/noripyt/django-cachalot/ 

I now also tried with django-mysql 3.6.0, but still no luck.

**Comment by adamchainz** [comment]
Cachalot seems to be doing a lot of monkey patching. It’s likely the problem lies there.
