### ISSUE TITLE
Unable to use __boolean in filter in JSONField

### ISSUE THREAD

**Issue by zxalif** [adamchainz/django-mysql#693]
Summary: I have stored a boolean field in JSONField().
the field contains {"is_old": true}
But when I try to filter the field like
```
Model.objects.filter(extra_data__is_old=True)
```
it raise an error, 

```
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON)))  LIMIT 21' at line 1")
```

Django Version: *Django 2.2*

Database and version used: *mariadb:10.3.13*

Version: *Django-MySQL  3.7.1*

**Comment by adamchainz** [comment]
Django-MySQL's JSONField is not supported on MariaDB and I'm going to stop development on it. Please use the backport of the official JSONField from Django 3.1 instead: https://pypi.org/project/django-jsonfield-backport/
