### ISSUE TITLE
Error "Not a valid string." for ListCharField

### ISSUE THREAD

**Issue by sihcpro** [adamchainz/django-mysql#713]
Django Version: **Django 2.2.15**

Database and version used: **MySQL 8.0**

Version: **Django-MySQL 3.8.1**

Django Rest Framework Version: **3.10.3**

Summary: 

I used `ListCharField` for the column name `view_key`. When I tried to create a record, I got this error: "Not a valid string."
I found this error from the `is_valid` function in the views. I printed my data and my object before validate, and here is the result:

My data:
```json
{
    "index": 1,
    "name": "1",
    "card_type": "P",
    "view_key": [
        "name",
        "phone"
    ],
    "user": 1
}
```

My object:
```
    id = IntegerField(label='ID', read_only=True)
    index = IntegerField(max_value=2147483647, min_value=-2147483648)
    name = CharField(max_length=127)
    display = ChoiceField(choices=(('O', 'ONLYME'), ('F', 'FRIEND'), ('P', 'PUBLIC')), required=False)
    card_type = ChoiceField(choices=(('P', 'PERSONAL'), ('B', 'BUSINESS')))
    data = ModelField(model_field=<django_mysql.models.fields.json.JSONField: data>, required=False)
    view_key = CharField(max_length=511)
    date_created = DateTimeField(read_only=True)
    date_updated = DateTimeField(read_only=True)
    user = PrimaryKeyRelatedField(queryset=SUsers.objects.all())
    template = PrimaryKeyRelatedField(allow_null=True, queryset=STemplates.objects.all(), required=False)
```

My models:
```python
class SCards(models.Model):
    ONLYME = "O"
    FRIEND = "F"
    PUBLIC = "P"
    DISPLAY = (
        (ONLYME, "ONLYME"),
        (FRIEND, "FRIEND"),
        (PUBLIC, "PUBLIC"),
    )

    PERSONAL = "P"
    BUSINESS = "B"
    CARD_TYPE = (
        (PERSONAL, "PERSONAL"),
        (BUSINESS, "BUSINESS"),
    )

    user = models.ForeignKey(SUsers, models.DO_NOTHING)
    template = models.ForeignKey(STemplates, models.DO_NOTHING, null=True)

    index = models.IntegerField()
    name = models.CharField(max_length=127)
    display = models.CharField(max_length=1, default=PUBLIC, choices=DISPLAY)
    card_type = models.CharField(max_length=1, choices=CARD_TYPE)

    data = JSONField()
    view_key = ListCharField(
        base_field=models.CharField(max_length=31),
        size=16,
        max_length=(16 * 32 - 1),
    )
```

I saw your example is quite easy [hear](https://django-mysql.readthedocs.io/en/latest/model_fields/list_fields.html), so, what is the problem?
Thank you.

**Comment by adamchainz** [comment]
> My object:

As I understand from the code, this is the inside of a Django Rest Framework serializer. You've declared `view_key = CharField(max_length=511)`. This only accepts incoming strings. I think you want a [ListField](https://www.django-rest-framework.org/api-guide/fields/#listfield):

```
view_key = serializers.ListField(
   child=serializers.CharField()
)
```

Hope that helps.

On your bug report - in future please include *the stack trace* or the full example error response, and the *`class` line* for every class you're showing. I had to guess what type of class your serializer is.

**Comment by sihcpro** [comment]
There are **no** `stack trace`. Everything I got in terminal is:

```bash
Bad Request: /api/cards/
[06/Oct/2020 08:23:10] "POST /api/cards/ HTTP/1.1" 400 36
```

And on browser, I got:

```json
{
    "view_key": [
        "Not a valid string."
    ]
}
```

Next time, I will more carefully.

Your answer fixed my problem, many thanks.

**Comment by adamchainz** [comment]
The example does not need updating. The example covers models. Your problem is within DRF serializers which aren't even mentioned in the Django-MySQL documentation.
