### ISSUE TITLE
Django makemigrations command doesn't add JSONField() type

### ISSUE THREAD

**Issue by mashahabi15** [adamchainz/django-mysql#731]
Hello everybody. I recently read django-mysql documents [here](https://django-mysql.readthedocs.io/en/latest/) . I have a field called _year_of_entry_ and its type was _IntegerField_ but I wanted to change it to _JSONField_. So I did:

- I installed django-mysql, then added it to INSTALLED_APPS list in settings.py file.

- `./manage.py check` didn't result any errors.

- I changed `year_of_entry = models.IntegerField(null=True)` to `year_of_entry = JSONField()`

- I ran `python3 manage.py makemigrations` but it resulted:

>  Migrations for 'reserve':
>   reserve/migrations/0008_remove_campaignentity_year_of_entry.py
>     - Remove field year_of_entry from campaignentity

Why it is removing _year_of_entry_? I know that django couldn't recognize the field type. I searched a lot but couldn't find any similar issue. Where do I have mistake?

Thank you for your consideration of my problem.

Django Version: *Django 2.2.0*
Python Version: *Python 3.6.9*
Database : *MySQL 8.0.21*
*pymysql 0.10.1*
*Django-MySQL 3.9.0*

**Comment by adamchainz** [comment]
Thanks for a clear error report.

Django 3.1 includes a cross-DB JSONField. Please use that. On your older Django version, you can use [this backport package](https://pypi.org/project/django-jsonfield-backport/) by the author of the field in Django. I will be deprecating the JSONField from Django-MySQL soon so it's not worth starting a new usage of it now.

(As to the missing migration operation, whilst I recommend you move away - did you definitely use `django_mysql.models.JSONField` and not `django_mysql.forms.JSONField`?)
