### ISSUE TITLE
Feature request: Resizable Integer Fields

### ISSUE THREAD

**Issue by barseghyanartur** [adamchainz/django-mysql#749]
Summary: *Resizable Integer Fields*

Some of them are simply missing from Django (TinyIntegerField, MediumIntegerField, DoubleField).

As per specs for [MariaDB](https://mariadb.com/kb/en/data-type-storage-requirements/#numeric-data-types) or [MySQL](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-numeric)

**Comment by adamchainz** [comment]
I think this would be better as a Django core feature suggestion. I think most of these sizes exist on all database backends.
