### ISSUE TITLE
TypeError: iterator() got an unexpected keyword argument 'chunk_size'

### ISSUE THREAD

**Issue by vaudric** [adamchainz/django-mysql#752]
Summary: the iterator doesn't support the chunk_size argument of the core Django QuerySet iterator function 

The following code in django_mysql.models.query line 157 - 160 fixes the problem.
    def iterator(self, **kwargs):
        if getattr(self, "_found_rows", 0) is None:
            raise ValueError("sql_calc_found_rows() doesn't work with iterator()")
        return super().iterator(**kwargs)

Django Version: 3.1.5
Database and version used: mariadb 10.14
Version: Django-MySQL 3.8.0

**Comment by adamchainz** [comment]
Fix released in version 3.11.1!

**Comment by vaudric** [comment]
Phenomenal. Thanks so much Adam!
