### ISSUE TITLE
is this package suport mysql set type

### ISSUE THREAD

**Issue by mthri** [adamchainz/django-mysql#781]
Hi,
In the document I looking for native MySql set type,  but i found [this](https://django-mysql.readthedocs.io/en/latest/model_fields/set_fields.html)
in CRUD operation this field has same performance as `Set Type` in MySql?

**Comment by adamchainz** [comment]
The set fields use strings and MySQL's `FIND_IN_SET` function rather than the `SET` type. This is spelled out in the first paragraph of the docs:

> Two fields that store sets of a base field in comma-separated strings - cousins of Django’s CommaSeparatedIntegerField. There are two versions: SetCharField, which is based on CharField and appropriate for storing sets with a small maximum size, and SetTextField, which is based on TextField and therefore suitable for sets of (near) unbounded size (the underlying LONGTEXT MySQL datatype has a maximum length of 232 - 1 bytes).
