### ISSUE TITLE
Passing enum.Enum to EnumField raises django.db.utils.DataError (Data truncated)

### ISSUE THREAD

**Issue by le717** [adamchainz/django-mysql#904]
### Python Version

3.7.9

### Django Version

3.2.13

### MariaDB/MySQL Version

MySQL 8.0.27

### Package Version

4.5.0

### Description

If I pass a member of an [`Enum`](https://docs.python.org/3/library/enum.html) to an `EnumField`, a `django.db.utils.DataError` exception is raised. I would expect to be able to pass a member directly to the field and it save to the database, assuming the member `.value` is defined in the enum. This exception is creating an awkward issue where native Enum values are expected to be returned from methods that provide info to be written directly to a database via the Django ORM but cannot be be without a series of one-off middle-man methods to pull out the `.value`.

I'm fully sure if this is something that should be filed or can be fixed here but I wanted to start here because I am hitting this using `EnumField`.

### Samples
- App [enumbug.zip](https://github.com/adamchainz/django-mysql/files/8475153/enumbug.zip)
- Traceback [python-traceback.txt](https://github.com/adamchainz/django-mysql/files/8475171/python-traceback.txt)
Install the `requirements.txt` and run `python manage.py migrate app` to trigger error after setting db connection settings. Relevant code is in `app/models.py` and `app/migrations/0002`.

**Comment by adamchainz** [comment]
Use [django's `enum.Enum` subclasses](https://adamj.eu/tech/2020/01/27/moving-to-django-3-field-choices-enumeration-types/) and the `.choices` properties they provide.

This could do with doucmenting, if you'd like to make a PR there.

**Comment by le717** [comment]
I keep forgetting to reply to this. It took me a while to try that out, but it worked perfectly. Thank you very much!

> This could do with doucmenting, if you'd like to make a PR there.
I genuinely wish I had the time for that. I can barely make any OSS contributions right now. :(
