### ISSUE TITLE
Clarification on migration from `utf8` to `utf8mb4` 

### ISSUE THREAD

**Issue by msf-dev** [adamchainz/django-mysql#959]
### Description

I've gone through the [django-mysql's docs](https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4) the linked [article](https://mathiasbynens.be/notes/mysql-utf8mb4), another [article](https://saveriomiroddi.github.io/An-in-depth-dbas-guide-to-migrating-a-mysql-database-from-the-utf8-to-the-utf8mb4-charset/) _(helpful conceptual explanation)_ and the discussion in #216. 

Although these are extremly helpful, It seems like they are a bit outdated and I'm unsure of what converting from `utf8` to `utf8mb4` looks like "today". It seems a lot easier as of MySQL 5.7.9 – so much so I feel like it's to good to be true and that I'm missing something 😅. 

1. Provided that you're using  `innodb_default_row_format=DYNAMIC` ([default for 5.7.9](https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-conversion.html)) and ```ALTER TABLE `my_table` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;```  will automagically update each column's character set and collation, why is it necessary to do `.. CHANGE column_name column_name ...`?

2. Assuming that fixing each column is necessary, would you then need to go through all models having `models.CharField`with a  `max_length > 191` and change them to be 191 to ensure django's model definition/migration aligns with the schema? 

If anyone could shed some light on this it would be greatly appreciated!

**Comment by adamchainz** [comment]
It’s been so long since I confronted did migration that I cannot remember any of the details. Afraid I can’t help you without doing a bunch of research.

Try checking the MariaDB docs, they’re often a bit more helpful on practical advice. For example, the charsets and collations page: https://mariadb.com/kb/en/setting-character-sets-and-collations/

I’ll leave this open in case other users want to answer but I think it’s unlikely.

**Comment by msf-dev** [comment]
> 

No worries and appreciate the reference.

**Comment by msf-dev** [comment]
Wanted to follow up and say thanks again for the reference – it gave me the answers I was looking for! I created a bash script to automate the process described in the [article](https://mathiasbynens.be/notes/mysql-utf8mb4) for InnoDB and thought it may help someone else using MySQL 5.7.X trying to do the same!

---
  ```sh
  #!/bin/bash
  # Modified from https://github.com/fleio/utf8mb4-convert
  
  set -e
  
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  
  show_help() {
    local help_text="
  Converts a database, and it's tables, charset from utf8 to utf8mb4 and utf8mb4_unicode_ci collation.
  All given parameters are directly given to the mysql command. Include the database name at a minimum
  and then any connection params (e.g. user, password, host, port, socket, etc.). For example:
  
    $ convert_to_utf8mb4.sh <database_name> [connection parameters ...]
  
  "
    echo "$help_text"
  }
  
  database="$1"
  
  confirm_continuation() {
    read -r confirmed
    if [ "$confirmed" != "y" ] && [ "$confirmed" != "Y" ]; then
      echo "Exiting ..."
      exit
    fi
  }
  
  if [ -z "$database" ]; then
    echo "${RED}Database name argument is required.${NC} (For help, enter convert_to_utf8mb4.sh -h)"
    echo ""
    exit 1
  elif [ "$database" = "-h" ] || [ "$database" = "--help" ]; then
    show_help
    exit 0
  else
    query_generator=$'SET @TARGET_DB := "'$database'";
  SELECT  -- Convert DB
      CONCAT("ALTER DATABASE `",
              @TARGET_DB,
              "` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;") AS sql_expressions
  
  UNION SELECT -- Convert tables
      CONCAT("ALTER TABLE `",
              TABLE_NAME,
              "` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;") AS sql_expressions
  FROM
      INFORMATION_SCHEMA.TABLES
  WHERE
      TABLE_SCHEMA = @TARGET_DB
          AND TABLE_TYPE LIKE "BASE TABLE"
  UNION SELECT  -- Analyze & rebuild each table
      CONCAT("OPTIMIZE TABLE `", TABLE_NAME, "`;") AS sql_expressions
  FROM
      INFORMATION_SCHEMA.TABLES
  WHERE
      TABLE_SCHEMA = @TARGET_DB
          AND TABLE_TYPE LIKE "BASE TABLE";
  '
    echo ""
    echo "This script will convert the entire database '$database' to utf8mb4 and then rebuild all tables."
    output="$(echo "$query_generator" | mysql $*)"
    generated_queries="$(echo "$output" | tail -n +2)"
  
    echo "Would you like to preview the SQL statements that will be executed? [y/N]:"
    read -r preview_sql
    if [ "$preview_sql" = "y" ] || [ "$preview_sql" = "Y" ]; then
      echo "Queries to convert database to utf8mb4:"
      echo "$generated_queries"
      echo ""
    fi
  
    echo "Would you like to write these queries to a file? [y/N]:"
    read -r write_to_file
    if [ "$write_to_file" == "y" ] || [ "$write_to_file" == "Y" ]; then
      echo "Enter the file name and path (ctrl+c to exit):"
      read -r file_name
      echo "$generated_queries" > "$file_name"
      echo "Queries written to $file_name"
      echo ""
      echo "To execute the queries, run the following command:"
      echo "mysql [connection parameters ...] '$database' < $file_name"
      echo ""
      echo "Exiting ..."
      exit
    fi
  
    echo "Would you like to apply these queries to the database directly? [y/N]:"
    confirm_continuation
    echo "You did create a backup for '$database', right? [y/N]:"
    confirm_continuation
    echo ""
    echo "  This may take a while, depending on your database size ..."
    echo ""
    echo "$generated_queries" | mysql $*
  fi
  
  ```

**Comment by adamchainz** [comment]
Great! Nice work. Perhaps try writing a blog post for discoverability?

**Comment by msf-dev** [comment]
Great idea!
