### ISSUE TITLE
Add support for natural sorting with MariaDB 10.7+ `NATURAL_SORT_KEY`

### ISSUE THREAD

**Issue by violuke** [adamchainz/django-mysql#975]
### Description

It would be great to be able to sort by [NATURAL_SORT_KEY](https://mariadb.com/kb/en/natural_sort_key/).

Possibly the following could be supported for the syntax (to natsort by the `name` column):

```python
Document.objects.order_by("NATURAL_SORT_KEY(name)")
```

Thanks

**Comment by adamchainz** [comment]
We'd want ot implement this as a database function. It would then use the syntax:

```py
Document.objects.order_by(NaturalSortKey("name"))
```

This isn't that much work - afaict it only needs a single argument database function. We have plenty of examples of that already. Would you like to try creating a PR?

**Comment by violuke** [comment]
Could you point me in the right direction, and I'll give it a go? Thanks

**Comment by adamchainz** [comment]
Sorry that after seeing how simple the database function is, I decided it’s not worth the maintenance burden.
